{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import time\n",
    "import socket\n",
    "from keyboard import is_pressed\n",
    "\n",
    "ip = \"192.168.193.102\"\n",
    "port = 8089\n",
    "msg = b\" \"\n",
    "while True :\n",
    "    try:\n",
    "        if is_pressed('w'):\n",
    "            msg = b'w'\n",
    "        elif is_pressed('a'):\n",
    "            msg = b'a'\n",
    "        elif is_pressed('s'):\n",
    "            msg = b's'\n",
    "        elif is_pressed('d'):\n",
    "            msg = b'd'\n",
    "        elif is_pressed('j'):\n",
    "            msg = b'j'\n",
    "        elif is_pressed('k'):\n",
    "            msg = b'k'\n",
    "        elif is_pressed('l'):\n",
    "            msg = b'l'\n",
    "    except:\n",
    "        break\n",
    "        \n",
    "    \n",
    "\n",
    "    print(f'Sending {msg} to {ip}:{port}')\n",
    "\n",
    "    sock = socket.socket(socket.AF_INET,\n",
    "                            socket.SOCK_DGRAM)\n",
    "    sock.sendto(msg, (ip, port))\n",
    "    time.sleep(0.2)\n",
    "    msg = b' '\n"
   ]
  }
